import "@/styles/globals.css";
import { Toaster } from "sonner";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
export const metadata: Metadata = {
  title: "DevInsights",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    //the top bar 
    <ClerkProvider>

    {/* the main part */}
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider> 
        <Toaster richColors/> 
      </body>
    </html>
    </ClerkProvider> //this is using the middleware to protect the routes
  );
}
